import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  introContainer: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  introScrollView: {
    flex: 1,
  },
  introScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  introContent: {
    backgroundColor: '#16213e',
    borderRadius: 20,
    padding: 20,
    maxWidth: 600,
    width: '100%',
    borderWidth: 2,
    borderColor: '#6B73FF',
    shadowColor: '#6B73FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  difficultyBadge: {
    backgroundColor: '#4ade80',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 15,
  },
  difficultyText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  scenarioTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 15,
    lineHeight: 32,
  },
  scenarioDescription: {
    color: '#a8b2d1',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 20,
  },
  introButtonContainer: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    marginTop: 10,
  },
  playButton: {
    backgroundColor: '#6B73FF',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    elevation: 5,
    shadowColor: '#6B73FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  playButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  backButtonIntro: {
    backgroundColor: '#e74c3c',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    elevation: 5,
    shadowColor: '#e74c3c',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  backButtonIntroText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  video: {
    flex: 1,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 50,
    left: 50,
    right: 50,
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#6B73FF',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    marginBottom: 10,
    minWidth: 150,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  goBackButton: {
    backgroundColor: '#ccc',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  goBackText: {
    color: '#333',
    fontSize: 16,
    textAlign: 'center',
  },
  choicesContainer: {
    position: 'absolute',
    bottom: 50,
    left: 50,
    right: 50,
    alignItems: 'center',
    gap: 15,
  },
  choiceButton: {
    backgroundColor: '#6B73FF',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    minWidth: 200,
  },
  choiceButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  title: {
    position: 'absolute',
    bottom: 200,
    left: 50,
    right: 50,
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  congratsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  congratsText: {
    color: '#fff',
    fontSize: 48,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  closeButton: {
    backgroundColor: '#6B73FF',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  subtitleContainer: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    borderLeftWidth: 6,
    borderLeftColor: '#FFD700',
    paddingVertical: 20,
    paddingHorizontal: 25,
    borderRadius: 8,
  },
  subtitleText: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '500',
  },
  subtitleCursor: {
    color: '#FFD700',
    fontSize: 16,
    fontWeight: 'bold',
  },
  characterDialogueContainer: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    borderRadius: 12,
    padding: 20,
    borderWidth: 2,
    borderColor: '#6B73FF',
  },
  characterName: {
    position: 'absolute',
    top: 10,
    left: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 4,
  },
  characterNameText: {
    color: '#FFD700',
    fontSize: 14,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  characterDialogueText: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
  },
  nextArrow: {
    position: 'absolute',
    bottom: 15,
    right: 20,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  persona5ChoicesContainer: {
    position: 'absolute',
    bottom: 180,
    right: 20,
    gap: 15,
  },
  persona5ChoiceButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#6B73FF',
    minWidth: 250,
  },
  persona5ChoiceButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  persona3CongratsCard: {
    backgroundColor: '#1a1a2e',
    borderWidth: 3,
    borderColor: '#4A90E2',
    borderRadius: 8,
    padding: 30,
    width: '85%',
    alignItems: 'center',
  },
  persona3CongratsTitle: {
    color: '#4A90E2',
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 15,
  },
  persona3Divider: {
    width: '100%',
    height: 2,
    backgroundColor: '#4A90E2',
    marginBottom: 20,
  },
  persona3CongratsMessage: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 20,
  },
  persona3CongratsValue: {
    color: '#FFD700',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 25,
    letterSpacing: 1,
  },
  persona3BackButton: {
    backgroundColor: '#4A90E2',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 4,
  },
  persona3BackButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  skipButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: 'rgba(255, 59, 48, 0.9)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    zIndex: 1000,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  skipButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  badEndingCard: {
    borderColor: '#DC2626',
  },
  badEndingTitle: {
    color: '#DC2626',
  },
  badEndingDivider: {
    backgroundColor: '#DC2626',
  },
  badEndingValues: {
    color: '#DC2626',
  },
  tryAgainButton: {
    backgroundColor: '#DC2626',
  },
});
