// scripts/update_lesson1.js
// Update lesson id=1 title and content in the local SQLite DB

const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.resolve(__dirname, '..', 'src', 'database', 'scisteps.db');
const db = new sqlite3.Database(dbPath);

const newTitle = 'Gamit ng Isip at Kilos-loob sa Sariling Pagpapasiya at Pagkilos';
const newContent = `Ano ang pagkakaiba ng isip ng tao sa isip ng hayop?
Ang ating isip ay higit na matalino.

Ang matalinong isip ng tao, masasabing matalino ang isip ng tao dahil sa pamamagitan nito ay ginagawa nating:
1. Umunawa at Matuto – Kakayahan ng isip ng tao na intindihin ang mga bagay, ideya, at karanasan, at mula rito ay matuto ng mga bagong kaalaman o aral.
2. Magnilay – Ang kakayahan na pag-isipan nang malalim ang isang pangyayari o ideya upang makuha ang mas malalim na kahulugan at matukoy ang kaugnayan nito sa sariling buhay.
3. Magbigay ng Kahulugan – Ang isip ng tao ay nakabubuo ng paliwanag at interpretasyon sa mga bagay na nakikita, naririnig, o nararanasan.
4. Umalala – Ang kakayahan na balikan at sariwain ang mga nakaraang karanasan, kaalaman, o pangyayari bilang gabay sa kasalukuyan.
5. Magsuri – Tumutukoy sa kakayahang mag-analisa at maghimay-himay ng impormasyon upang makita ang katotohanan, kahinaan, at kalakasan ng isang bagay.
6. Tumuklas o Imbento – Sa pamamagitan ng pag-iisip, nagagawa ng tao na makabuo ng bagong ideya, tuklasin ang bago, at lumikha ng mga imbensyon na makatutulong sa buhay.
7. Humusga – Ang isip ng tao ay may kakayahang magpasya kung tama o mali, mabuti o masama, batay sa natutunang aral at sariling pananaw.
8. Mangatwiran o Magbigay ng Dahilan – Ang tao ay may talino upang ipaliwanag at bigyang katuwiran ang kanyang iniisip, pinaniniwalaan, o ginagawa.

Ang tunguhin ng isip - ito ay pagtuklas ng katotohanan, kaalaman, at karunungan (pagpapakatalino at pagpapakadunong)
Ang mataas na gamit ng isip - pag-aaral at pagsasaliksik
Ang kilos-loob (will) - ito ay malaya kaya tinatawag din itong “free will”, isninasakatuparang ang sinasabi ng isip, taglay natin kung kaya’t  nagagawa nating umayaw o gumusto
Ang tunguhin ng kilos-loob (will) - pagmamahal o pag-ibig
Ang mataas na gamit ng kilos-loob - paggawa ng kabutihan`;

db.serialize(() => {
  // Check if lesson id=1 exists
  db.get('SELECT id FROM lessons WHERE id = 1', (checkErr, row) => {
    if (checkErr) {
      console.error('Error checking lesson existence:', checkErr);
      process.exit(1);
    }

    if (row && row.id) {
      // Update existing
      db.run(`UPDATE lessons SET title = ?, content = ? WHERE id = 1`, [newTitle, newContent], function(err) {
        if (err) {
          console.error('Error updating lesson:', err);
          process.exit(1);
        }
        console.log('Updated lesson rows:', this.changes);
        db.get('SELECT id, unit_id, title, content FROM lessons WHERE id = 1', (err2, updated) => {
          if (err2) { console.error('Error selecting updated lesson:', err2); process.exit(1); }
          console.log('Updated lesson record:\n', updated);
          db.close();
        });
      });
    } else {
      // Insert new lesson (id will be autogenerated)
      db.run(`INSERT INTO lessons (unit_id, title, content, duration_minutes) VALUES (?, ?, ?, ?)`, [1, newTitle, newContent, 15], function(insErr) {
        if (insErr) {
          console.error('Error inserting lesson:', insErr);
          process.exit(1);
        }
        const newId = this.lastID;
        console.log('Inserted lesson id:', newId);
        db.get('SELECT id, unit_id, title, content FROM lessons WHERE id = ?', [newId], (err3, inserted) => {
          if (err3) { console.error('Error selecting inserted lesson:', err3); process.exit(1); }
          console.log('Inserted lesson record:\n', inserted);
          // Also create a lesson_page for page 1
          db.run(`INSERT INTO lesson_pages (lesson_id, page_number, title, content) VALUES (?, ?, ?, ?)`, [newId, 1, 'Lesson 1', newContent], (lpErr) => {
            if (lpErr) console.error('Error inserting lesson_page:', lpErr);
            else console.log('Inserted lesson_page for lesson id', newId);
            db.close();
          });
        });
      });
    }
  });
});
