import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  stickyHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingTop: 0, // Reduced top spacing for sticky header
    paddingHorizontal: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  backButton: {
    padding: 6,
    marginRight: 6,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E293B',
    flex: 1,
    textAlign: 'center',
    lineHeight: 20,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  readingTime: {
    fontSize: 12,
    color: '#64748b',
  },
  themeToggle: {
    padding: 6,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
  },
  progressBar: {
    height: 3,
    backgroundColor: '#e2e8f0',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 2,
  },
  scrollContent: {
    paddingTop: 100, // Account for sticky header
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  section: {
    marginBottom: 16,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#047857', // Green-700 for emphasis
    letterSpacing: 0.3,
  },
  body: {
    fontSize: 16,
    color: '#1f2937', // Darker gray for better readability
    lineHeight: 26,
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  keyTerm: {
    fontWeight: '700',
    textDecorationLine: 'underline',
    backgroundColor: '#fef3c7', // Subtle yellow highlight
    paddingHorizontal: 2,
    borderRadius: 2,
  },
  reflectionBox: {
    marginBottom: 20,
    borderRadius: 12,
    padding: 18,
    borderLeftWidth: 6,
    borderLeftColor: '#10B981',
    backgroundColor: '#f0fdf4', // Very light green
  },
  reflectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#047857', // Green-700
    marginBottom: 10,
  },
  reflectionText: {
    fontSize: 15,
    color: '#475569',
    fontStyle: 'italic',
  },
  summaryBox: {
    borderWidth: 3,
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
  },
  summaryText: {
    fontSize: 15,
    color: '#334155',
    fontWeight: '500',
    lineHeight: 22,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
    marginBottom: 40,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 8,
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
  },
  secondaryButtonText: {
    color: '#10B981',
  },
  scrollTopButton: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    backgroundColor: '#10B981',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    margin: 20,
    borderRadius: 12,
    padding: 20,
    width: '80%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 12,
  },
  modalText: {
    fontSize: 16,
    color: '#334155',
    lineHeight: 22,
    marginBottom: 20,
  },
  modalCloseButton: {
    backgroundColor: '#10B981',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignSelf: 'flex-end',
  },
  modalCloseText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  brainModelContainer: {
    alignItems: 'center',
    padding: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#10B981',
    borderStyle: 'dashed',
  },
  brainModelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#334155',
    marginTop: 12,
    textAlign: 'center',
  },
  brainModelSubtext: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 4,
    textAlign: 'center',
  },
  pullQuote: {
    marginTop: 20,
    paddingLeft: 20,
    paddingRight: 16,
    paddingVertical: 16,
    borderLeftWidth: 5,
    borderRadius: 8,
  },
  quoteText: {
    fontSize: 16,
    fontStyle: 'italic',
    lineHeight: 24,
    color: '#047857', // Green text for quotes
    fontWeight: '500',
  },
  summaryLabel: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  sectionSubheading: {
    fontSize: 17,
    fontWeight: '600',
    color: '#d97706',
    marginTop: 12,
    marginBottom: 8,
  },
  exampleItem: {
    fontSize: 15,
    color: '#374151',
    lineHeight: 24,
    marginBottom: 6,
  },
  termCard: {
    marginBottom: 16,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  termText: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  definitionText: {
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 16,
  },
  halimbawaContainer: {
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 12,
  },
  halimbawaText: {
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
  },
});
